# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kaldrenon
email: kaldrenon@gmail.com
author: Andrew Fallows
description: >- # this means to ignore newlines until "baseurl:"
  My personal landing page online. Look here for contact info,
  the occasional infrequent blog post, and links to things I
  hope you will find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kaldrenon
github_username:  kaldrenon

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gallery-generator

gallery:
  dir: art                # Path to the gallery
  symlink: false          # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Art"            # Title for gallery index page
  title_prefix: "Art: "   # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time" # How to sort galleries on the index page.
